[build]  
  publish = "dist"
  command = "npm run build" 

[[headers]]  
  for = "https://hcateringback-dev.unitbeandev.com/api*"  
  https://hcateringback-dev.unitbeandev.com/api
  [headers.values]  
    Access-Control-Allow-Origin = "*"  
    Access-Control-Allow-Methods = "GET, POST, PATCH"  
    Access-Control-Allow-Headers = "Content-Type" 